- dist/neo.blockchain.node.js
Pure comment changes.
Untested JSDoc tag additions, @lllwvlvwlll can you compile the documentation and help me cross check for odd appearance? Thank you.
> Add some @example tags

- dist/neo.blockchain.node.js
To address the syntax error from #15
> Syntax bug fix in invoke method.

- dist/neo.blockchain.neo.js
Update to ES6 and use standard code style https://github.com/standard/standard
> Update neo.blockchain.neo to ES6

- dist/neo.blockchain.neo.js
To satersfy all style warnings prompted from `standard`.
> Coding style update on neo.blockchain.neo.js

- dist/neo.blockchain.sync.js
To satersfy all style warnings prompted from `standard`.
> Coding style update on neo.blockchain.sync.js

- dist/neo.blockchain.node.js
To satersfy all style warnings prompted from `standard` as well as standardise code indentions.
> Coding style update on  neo.blockchain.node.js

- dist/neo.blockchain.neo.js
- dist/neo.blockchain.sync.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
Structures some of the files for legibility and also adds support for data verification at a model-level
Scalability and support for verification methods
Full testnet sync
> code structure and verify method

- dist/node/storage.js
- dist/node/storage/mongodb.js
> minor syntax enhancements

- examples/nodejs/rpc/basic.js
First basic RPC example code.
This is the initial step to start accumulate bite-size, self-documented examples to assist new developer on-boarding.
> RPC example usage

- dist/neo.blockchain.sync.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
> asynchronous syncing and script storage

- dist/node/util/rpc.js
- examples/nodejs/rpc/contract.js
- test/helpers/mock-responses.js
- test/helpers/profiles.js
- test/helpers/test-helper.js
- test/integration/node/util/rpc/contract.js
- test/unit/node/util/rpc/contract.js
Add getContractState RPC method
> Add getContractState RPC method

- .github/CONTRIBUTING.md
- README.md
* Better align with CityOfZion project's README format
* Update usage example
* Add new subsections in both README and CONTRIBUTING documents
> Documentation updates

- package.json
Bug fix on `npm run lint` definitely which was incorrect and fails silently.
> Correct 'npm run lint' pathing

- dist/node/mesh.js
- dist/node/rpc.js
- dist/node/storage.js
- package.json
Non-implementation updates, purely comment and indention amendments.
> JavaScript linting

- dist/node/storage.js
> Fix style warning

- dist/node/storage/mongodb.js
- examples/nodejs/node/sync.js
- package.json
- test/helpers/mock-responses.js
- test/integration/node/util/rpc/contract.js
- test/unit/node/util/rpc/contract.js
Improve/correct ESLint coverage.
> Correct ESLint coverage

- dist/node/mesh.js
- dist/node/rpc.js
Starting a small refactor on the way promise are handled in `rpc.js` file. instead of creating some Promise over and over just chain it as many time you want.
It doesn't fix an open issue, but it simplify a lot of current `rpc.js` file. Note that the `call` function should be defined before everything to ease the reading.
Next step is to refacto `storage.js` aswell.
I've just run the test and all are passing atm
(none, just styling)
> Clean Promise in RPC.js, + Some code style for network selection

- dist/node.js
- dist/node/mesh.js
- dist/profiles.js
- examples/nodejs/node/privNetSetup.js
- examples/nodejs/node/sync.js
- examples/nodejs/rpc/endpoints.js
- test/helpers/test-helper.js
To improve legibility of the code in `mesh.js` and propose a less confusing naming convention of optional properties.
* Introduce a new `profiles.js` file, designed to store all static values. I picked `.js` over `.json` for potential calculation usage or complex data type in the future.
* It is no longer valid to *not* to provide `options.network` value.
* Provided `options.network` property can be either string (expected to be 'testnet' or 'mainnet') or an object.
* The word usage for `seeds` has been replaced with `endpoints` as the word "seed" is to be reserved for another purpose.
To improve legibility, reduce potential human error and ease onboarding process for new contributors.
> Node network support clean up

- test/integration/node/util/rpc/address.js
- test/integration/node/util/rpc/asset.js
- test/integration/node/util/rpc/block.js
- test/integration/node/util/rpc/contract.js
- test/integration/node/util/rpc/node.js
- test/integration/node/util/rpc/transaction.js
- test/integration/node/util/rpc/wallet.js
Integration test cases was broken from `0.5.0`. This PR looks into addressing and recover its original functionality.
> Fix integration test cases

- package.json
Add `documentation` package into the build script.
Repo docs can now be regenerated with command:
* `npm run build:docs`
To simplify the process of updating documentations, as well as eliminate global dependencies that may vary between developers.
N/A
> Add documentation package into the build script

- README.md
Add build badges to `README` file.
> Add build badges to README file

- examples/node/asset.js
- examples/node/privatenet.js
- examples/node/sync-test.js
- examples/node/sync.js
- examples/rpc/basic.js
- examples/rpc/contract.js
- examples/rpc/endpoints.js
- examples/rpc/light-wallet.js
Address incorrect reference paths caused from #115
> Fix relative paths in examples

- dist/node.js
Correct usage of promise reject behaviour in `node.js` file.
> Correct usage of promise reject behaviour

- examples/node/privatenet.js
Correct MongoDB optional property name usage in `privatenet.js` example from `seeds` to `endpoints`.
> Correct MongoDB optional property name

- dist/common/logger.js
- dist/node.js
- dist/node/mesh.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/wallet.js
- examples/common/logger.js
- examples/node/asset.js
- examples/node/privatenet.js
- examples/node/sync-test.js
- examples/node/sync.js
- examples/rpc/basic.js
- examples/rpc/contract.js
- examples/rpc/endpoints.js
- examples/rpc/light-wallet.js
- package.json
Add a proper logger library instead of hard coded `console.log`.
> Add logger library

- dist/common/logger.js
> Correct default logging level

- package.json
> Update and correct mocha test scripts

- examples/rpc/endpoints.js
>  Update RPC endpoint example usage to provide better diagnostic data

- dist/common/hash-helper.js
- dist/node/storage/mongodb.js
- dist/wallet.js
- test/unit/common/hash-helper.js
> Create HashHelper and refactor its usage

- dist/neo.js
- dist/node/mesh.js
- dist/node/node.js
- dist/node/rpc.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/wallet.js
- docs/Mesh.html
- docs/MongodbStorage.html
- docs/Neo.html
- docs/Node.html
- docs/Rpc.html
- docs/Storage.html
- docs/Wallet.html
- docs/neo.js.html
- docs/node_mesh.js.html
- docs/node_node.js.html
- docs/node_rpc.js.html
- docs/node_storage.js.html
- docs/node_storage_mongodb.js.html
- docs/wallet.js.html
>  Add support for deep optional parameter assignment

- dist/node/rpc.js
- examples/rpc/endpoints.js
- package.json
- test/integration/node/rpc/block.js
- test/unit/node/rpc/address.js
- test/unit/node/rpc/asset.js
- test/unit/node/rpc/block.js
- test/unit/node/rpc/contract.js
- test/unit/node/rpc/node.js
- test/unit/node/rpc/transaction.js
- test/unit/node/wallet/core.js
Replace existing RPC implementations with neon-js's when available.
Class `Rpc` will still exists as a delegate since the interfaces are currently not exact matches.
This will reduce our code base, inheritently improve project manageability.
> Adapt neon-js in RPC implementation 

- test/unit/node/rpc/block.js
> Remove legacy unit test that breaks husky

- dist/neo.js
- dist/node/mesh.js
- dist/node/rpc.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/wallet.js
- examples/node/sync.js
Add comprehensive logging throughout the implementation to assist in debugging.
> Comprehensive event logging throughout code base

- dist/neo.js
- dist/node/mesh.js
- dist/node/node.js
- dist/node/rpc.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/wallet.js
Code refactor to remove `logger` as part of optional input parameter.
It'll always been initiated per class.
> Make logger services no longer part of optional input parameter

- dist/common/profiles.js
- examples/rpc/endpoints.js
> Update RPC node endpoints

- dist/node/storage/mongodb.js
> Better MongoDB connectivity error handling

- .gitignore
- .npmrc
- package-lock.json
- package.json
> Add NPM's lock file to project

- dist/neo.js
- examples/smoke-test/version.js
Add version property to both Neo class and instance
> Add version property to both Neo class and instance

- dist/common/validation-helper.js
- dist/neo.js
- dist/node/mesh.js
> Add node validator and simple usages

- dist/neo.js
- dist/node/mesh.js
- dist/node/node.js
- dist/node/rpc.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/wallet.js
- examples/smoke-test/asset.js
- examples/smoke-test/block-count.js
- test/integration/node/rpc/transaction.js
> Clean up ESLint ignore usages

- README.md
- examples/smoke-test/mesh-rpc.js
Correct `README.md` example and pair with an example script.
> Update example on README

- dist/neo.js
- dist/node/mesh.js
- dist/node/node.js
- dist/node/rpc.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/wallet.js
- docs/Mesh.html
- docs/MongodbStorage.html
- docs/Neo.html
- docs/Node.html
- docs/Rpc.html
- docs/Storage.html
- docs/Wallet.html
- docs/index.html
- docs/neo.js.html
- docs/node_mesh.js.html
- docs/node_node.js.html
- docs/node_rpc.js.html
- docs/node_storage.js.html
- docs/node_storage_mongodb.js.html
- docs/wallet.js.html
Classes are to inherit from `EventEmitter` and each is capable of emitting events at different states.
This is at its initial adaptation stage where we'll be testing out its feasibilities before apply more practical usages from this feature.
> Add Event Emitters

- examples/common/logger.js
- examples/regression-test/validate-block.js
- examples/report/rpc-endpoints.js
- examples/smoke-test/asset.js
- examples/smoke-test/block-count.js
- examples/smoke-test/mesh-rpc.js
- examples/smoke-test/mongodb.js
- examples/smoke-test/rpc-privnet.js
- examples/smoke-test/rpc-testnet.js
- examples/smoke-test/sync-testnet.js
- examples/smoke-test/version.js
- examples/sync/mainnet.js
- examples/sync/privnet.js
- examples/sync/testnet.js
> Tweak and modernise all examples

- README.md
- dist/node/mesh.js
- dist/node/node.js
- examples/smoke-test/block-count.js
- examples/smoke-test/mesh-rpc.js
Design of mesh ready state (via event emitter) and update its usage on README
To provide actual mechanism to detect when mesh is ready to use.
> Mesh ready state

- dist/common/logger.js
- dist/common/validation-helper.js
- dist/neo.js
- dist/node/mesh.js
- dist/node/node.js
- dist/node/rpc.js
- dist/node/storage.js
- dist/node/storage/mongodb.js
- dist/strategy/sync-strategy.js
- dist/wallet.js
> JSDoc cleanup

- src/core/syncer.ts
For https://github.com/CityOfZion/neo-js/issues/177
> Mechanism to prevent Syncer.analyzeBlocks() overlaps

- src/core/syncer.ts
For https://github.com/CityOfZion/neo-js/issues/174
> Add a dedicated prune queue

- src/core/node.ts
> Verify and prevent Node.getShapedLatency() from returning NaN

- src/core/api.ts
> Add feature toggle in Api.getBlock() to optionally store block into storage

- src/core/api.ts
> Add ability for Api instance to emit 'ready' event
